export const ActionTypes = {
    SET_ALL_TASKS : "SET_ALL_TASKS",
    SET_UNASSIGNED_TASKS : "SET_UNASSIGNED_TASKS",
    SET_TODO_TASKS: "SET_TODO_TASKS",
    SET_ONGOING_TASKS: "SET_ONGOING_TASKS",
    SET_FINISHED_TASKS: "SET_FINISHED_TASKS",
    SET_CURRENT_STATUS: "SET_CURRENT_STATUS",
    SET_CURRENT_TASKS_USER: "SET_CURRENT_TASKS_USER",
    SET_IS_TASKS_BY_USER: " SET_IS_TASKS_BY_USER",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SELECTED_TASK : "SELECTED_TASK",
    SET_ALL_USERS: "SET_ALL_USERS",
    SET_CURRENT_USER_STATUS: "SET_CURRENT_USER_STATUS",
    SET_USER_TYPES: "SET_USER_TYPES",
    SET_TASK_PRIORITIES: "SET_TASK_PRIORITIES",
    SET_TASK_STATUS: "SET_TASK_STATUS"
};
